# Server settings (ServerProperties)
server:
  port: 8081
  address: 127.0.0.1
  sessionTimeout: 30
  servletPath: /
  contextPath: /drinkopedia

  # Tomcat specifics
  tomcat:
    accessLogEnabled: true
    basedir:
    backgroundProcessorDelay: 30 # secs
    
spring:
    jpa:
        generate-ddl: true
    datasource:
        initialize: true
    jersey:
        application-path: /api