# Server settings (ServerProperties)
server:
  port: 8081
  address: 127.0.0.1
  sessionTimeout: 30
  servletPath: /
  contextPath: /drinkopedia

  # Tomcat specifics
  tomcat:
    accessLogEnabled: true
    basedir:
    backgroundProcessorDelay: 30 # secs
    
debug: true

spring:
    jpa:
      show-sql: true
      #database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      properties:
        javax:
          persistence:
            schema-generation:
              create-source: metadata
              scripts:
                action: create
                create-target: create.sql
    #datasource:
    #    initialize: true
    #    url: jdbc:postgresql://localhost:5432/drinkopedia
    #    username: postgres
    #    password: postgres
    jersey:
        application-path: /api
        
#spring.datasource.url= jdbc:postgresql://localhost:5432/springbootdb
#spring.datasource.username=postgres
#spring.datasource.password=postgres@123
#spring.jpa.hibernate.ddl-auto=create-drop
        
security:
  user:
    name: belzeboss
    password: 666
    