# Server settings (ServerProperties)
server:
  port: 8081
  sessionTimeout: 30
  servlet:
    contextPath: /drinkopedia

  # Tomcat specifics
  tomcat:
    accessLogEnabled: true
    basedir:
    backgroundProcessorDelay: 30 # secs
    
#debug: true
management:
  endpoints:
    web:
      exposure:
        # DO NOT COPY IN PROD
        include: "health,info,httptrace"
spring:
  profiles:
    active: dev
  mvc:
    servlet:
      path: /
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
  datasource:
      url: jdbc:postgresql://localhost:5432/drinkopedia
      username: postgres
      password: postgres
#  security:
#    user:
#      name: belzeboss
#      password: 666
#    oauth2:
#      client:
#        registration:
#          okta:
#            client-id: 0oaaxvrmqiItRCkPj356
#            scope: openid, email, profile
#        provider:
#          okta:
#            issuer-uri: https://dev-824683.okta.com/oauth2/default
okta:
  oauth2:
    issuer: https://dev-824683.okta.com/oauth2/default
    client-id: 0oabhh3e7EfXqH83B356
    client-secret: SuwoogEha3WWVSYTnXCtMDjDXy8euzsSGHNSN4KY
    redirect-uri: /authorization-code/callback