# Server settings (ServerProperties)
server:
  sessionTimeout: 30

  # Tomcat specifics
  tomcat:
    accessLogEnabled: true
    basedir:
    backgroundProcessorDelay: 30 # secs
    
#debug: true

spring:
  profiles:
    active: dev
  mvc:
    servlet:
      path: /
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
  datasource:
      initialization-mode: always
      url: jdbc:postgresql://localhost:5432/drinkopedia
      username: postgres
      password: postgres
  security:
    user:
      name: belzeboss
      password: 666